#!/bin/bash
#
# Hacked from CHARMM-GUI (http://www.charmm-gui.org) v3.7

python -u openmm_run.py -i step4_equilibration.inp -t 4_apo_4XYJ_17-784_topol.top -g 4_apo_4XYJ_17-784_md.gro -orst step4_equilibration.rst -odcd step4_equilibration.dcd > step4_equilibration.out
